#!/bin/bash

# Define o nome do arquivo e a URL
SCRIPT_NAME="Waydroid-Updater.sh"
URL="https://raw.githubusercontent.com/ryanrudolfoba/SteamOS-Waydroid-Installer/refs/heads/main/extras/Waydroid-Updater.sh"

echo "Removendo versões antigas para evitar conflitos..."
rm -f ~/$SCRIPT_NAME*

echo "Baixando a versão mais recente..."
wget -q -O ~/$SCRIPT_NAME "$URL"

echo "Configurando permissões de execução..."
chmod +x ~/$SCRIPT_NAME

echo "Iniciando o instalador..."
~/./$SCRIPT_NAME
